# Generated by Django 2.1.2 on 2018-11-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_wallet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(default='up')),
                ('threshold', models.FloatField(default=-1)),
                ('type', models.TextField(default='up')),
                ('triggered', models.BooleanField(default=False)),
                ('old_price', models.FloatField(default=-1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Asset')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='asset_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_price_buy',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_price_sell',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='image',
            field=models.ImageField(default='profile_image/no_image.jpg', upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Wallet'),
        ),
    ]
