# Generated by Django 2.1.2 on 2018-11-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_auto_20181106_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned', models.FloatField(default=-1)),
                ('due_date', models.DateField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaned', models.FloatField(default=-1)),
                ('interest_rate', models.FloatField(default=-1)),
                ('days', models.IntegerField(default=-1)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Game.LoanOffer'),
        ),
    ]
