# Generated by Django 2.1.2 on 2018-11-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_auto_20181108_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanoffer',
            old_name='loaned',
            new_name='offered',
        ),
    ]
