# Generated by Django 2.1.2 on 2018-11-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='times',
            field=models.IntegerField(default=3),
        ),
    ]
