# Generated by Django 2.1.2 on 2018-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_auto_20181117_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
